const BOOKS = [
    { bookIndex: 1, bookId: 'genesis', name: 'Genesis', audioCode: 'GEN', folderName: '01-Genesis', testament: 'old' },
    { bookIndex: 2, bookId: 'exodus', name: 'Exodus', audioCode: 'EXO', folderName: '02-Exodus', testament: 'old' },
    { bookIndex: 3, bookId: 'leviticus', name: 'Leviticus', audioCode: 'LEV', folderName: '03-Leviticus', testament: 'old' },
    { bookIndex: 4, bookId: 'numbers', name: 'Numbers', audioCode: 'NUM', folderName: '04-Numbers', testament: 'old' },
    { bookIndex: 5, bookId: 'deuteronomy', name: 'Deuteronomy', audioCode: 'DEU', folderName: '05-Deuteronomy', testament: 'old' },
    { bookIndex: 6, bookId: 'joshua', name: 'Joshua', audioCode: 'JOS', folderName: '06-joshua', testament: 'old' },
    { bookIndex: 7, bookId: 'judges', name: 'Judges', audioCode: 'JUD', folderName: '07-judges', testament: 'old' },
    { bookIndex: 8, bookId: 'ruth', name: 'Ruth', audioCode: 'RUT', folderName: '08-Ruth', testament: 'old' },
    { bookIndex: 9, bookId: '1-samuel', name: '1 Samuel', audioCode: '1SA', folderName: '09-1samuel', testament: 'old' },
    { bookIndex: 10, bookId: '2-samuel', name: '2 Samuel', audioCode: '2SA', folderName: '10-2samuel', testament: 'old' },
    { bookIndex: 11, bookId: '1-kings', name: '1 Kings', audioCode: '1KI', folderName: '11-1kings', testament: 'old' },
    { bookIndex: 12, bookId: '2-kings', name: '2 Kings', audioCode: '2KI', folderName: '12-2kings', testament: 'old' },
    { bookIndex: 13, bookId: '1-chronicles', name: '1 Chronicles', audioCode: '1CH', folderName: '13-1chronicles', testament: 'old' },
    { bookIndex: 14, bookId: '2-chronicles', name: '2 Chronicles', audioCode: '2CH', folderName: '14-2chronicles', testament: 'old' },
    { bookIndex: 15, bookId: 'ezra', name: 'Ezra', audioCode: 'EZR', folderName: '15-ezra', testament: 'old' },
    { bookIndex: 16, bookId: 'nehemiah', name: 'Nehemiah', audioCode: 'NEH', folderName: '16-nehemiah', testament: 'old' },
    { bookIndex: 17, bookId: 'esther', name: 'Esther', audioCode: 'EST', folderName: '17-esther', testament: 'old' },
    { bookIndex: 18, bookId: 'job', name: 'Job', audioCode: 'JOB', folderName: '18-job', testament: 'old' },
    { bookIndex: 19, bookId: 'psalms', name: 'Psalms', audioCode: 'PSA', folderName: '19-psalms', testament: 'old' },
    { bookIndex: 20, bookId: 'proverbs', name: 'Proverbs', audioCode: 'PRO', folderName: '20-proverbs', testament: 'old' },
    { bookIndex: 21, bookId: 'ecclesiastes', name: 'Ecclesiastes', audioCode: 'ECC', folderName: '21-ecclesiastes', testament: 'old' },
    { bookIndex: 22, bookId: 'song-of-solomon', name: 'Song of Solomon', audioCode: 'SON', folderName: '22-songofsolomon', testament: 'old', sourceNames: ['Song of Solomon', 'Song of Songs'] },
    { bookIndex: 23, bookId: 'isaiah', name: 'Isaiah', audioCode: 'ISA', folderName: '23-isaiah', testament: 'old' },
    { bookIndex: 24, bookId: 'jeremiah', name: 'Jeremiah', audioCode: 'JER', folderName: '24-jeremiah', testament: 'old' },
    { bookIndex: 25, bookId: 'lamentations', name: 'Lamentations', audioCode: 'LAM', folderName: '25-lamentations', testament: 'old' },
    { bookIndex: 26, bookId: 'ezekiel', name: 'Ezekiel', audioCode: 'EZE', folderName: '26-ezekiel', testament: 'old' },
    { bookIndex: 27, bookId: 'daniel', name: 'Daniel', audioCode: 'DAN', folderName: '27-daniel', testament: 'old' },
    { bookIndex: 28, bookId: 'hosea', name: 'Hosea', audioCode: 'HOS', folderName: '28-hosea', testament: 'old' },
    { bookIndex: 29, bookId: 'joel', name: 'Joel', audioCode: 'JOE', folderName: '29-joel', testament: 'old' },
    { bookIndex: 30, bookId: 'amos', name: 'Amos', audioCode: 'AMO', folderName: '30-amos', testament: 'old' },
    { bookIndex: 31, bookId: 'obadiah', name: 'Obadiah', audioCode: 'OBA', folderName: '31-obadiah', testament: 'old' },
    { bookIndex: 32, bookId: 'jonah', name: 'Jonah', audioCode: 'JON', folderName: '32-jonah', testament: 'old' },
    { bookIndex: 33, bookId: 'micah', name: 'Micah', audioCode: 'MIC', folderName: '33-micah', testament: 'old' },
    { bookIndex: 34, bookId: 'nahum', name: 'Nahum', audioCode: 'NAH', folderName: '34-nahum', testament: 'old' },
    { bookIndex: 35, bookId: 'habakkuk', name: 'Habakkuk', audioCode: 'HAB', folderName: '35-habakkuk', testament: 'old' },
    { bookIndex: 36, bookId: 'zephaniah', name: 'Zephaniah', audioCode: 'ZEP', folderName: '36-zephaniah', testament: 'old' },
    { bookIndex: 37, bookId: 'haggai', name: 'Haggai', audioCode: 'HAG', folderName: '37-haggai', testament: 'old' },
    { bookIndex: 38, bookId: 'zechariah', name: 'Zechariah', audioCode: 'ZEC', folderName: '38-zechariah', testament: 'old' },
    { bookIndex: 39, bookId: 'malachi', name: 'Malachi', audioCode: 'MAL', folderName: '39-malachi', testament: 'old' },
    { bookIndex: 40, bookId: 'matthew', name: 'Matthew', audioCode: 'MAT', folderName: '40-matthew', testament: 'new' },
    { bookIndex: 41, bookId: 'mark', name: 'Mark', audioCode: 'MAR', folderName: '41-mark', testament: 'new' },
    { bookIndex: 42, bookId: 'luke', name: 'Luke', audioCode: 'LUK', folderName: '42-luke', testament: 'new' },
    { bookIndex: 43, bookId: 'john', name: 'John', audioCode: 'JOH', folderName: '43-john', testament: 'new' },
    { bookIndex: 44, bookId: 'acts', name: 'Acts', audioCode: 'ACT', folderName: '44-acts', testament: 'new' },
    { bookIndex: 45, bookId: 'romans', name: 'Romans', audioCode: 'ROM', folderName: '45-romans', testament: 'new' },
    { bookIndex: 46, bookId: '1-corinthians', name: '1 Corinthians', audioCode: '1CO', folderName: '46-1corinthians', testament: 'new' },
    { bookIndex: 47, bookId: '2-corinthians', name: '2 Corinthians', audioCode: '2CO', folderName: '47-2corinthians', testament: 'new' },
    { bookIndex: 48, bookId: 'galatians', name: 'Galatians', audioCode: 'GAL', folderName: '48-Galatians', testament: 'new' },
    { bookIndex: 49, bookId: 'ephesians', name: 'Ephesians', audioCode: 'EPH', folderName: '49-Ephesians', testament: 'new' },
    { bookIndex: 50, bookId: 'philippians', name: 'Philippians', audioCode: 'PHP', folderName: '50-Philippians', testament: 'new' },
    { bookIndex: 51, bookId: 'colossians', name: 'Colossians', audioCode: 'COL', folderName: '51-colossians', testament: 'new' },
    { bookIndex: 52, bookId: '1-thessalonians', name: '1 Thessalonians', audioCode: '1TH', folderName: '52-1thessalonians', testament: 'new' },
    { bookIndex: 53, bookId: '2-thessalonians', name: '2 Thessalonians', audioCode: '2TH', folderName: '53-2thessalonians', testament: 'new' },
    { bookIndex: 54, bookId: '1-timothy', name: '1 Timothy', audioCode: '1TI', folderName: '54-1timothy', testament: 'new' },
    { bookIndex: 55, bookId: '2-timothy', name: '2 Timothy', audioCode: '2TI', folderName: '55-2timothy', testament: 'new' },
    { bookIndex: 56, bookId: 'titus', name: 'Titus', audioCode: 'TIT', folderName: '56-titus', testament: 'new' },
    { bookIndex: 57, bookId: 'philemon', name: 'Philemon', audioCode: 'PHM', folderName: '57-philemon', testament: 'new' },
    { bookIndex: 58, bookId: 'hebrews', name: 'Hebrews', audioCode: 'HEB', folderName: '58-hebrews', testament: 'new' },
    { bookIndex: 59, bookId: 'james', name: 'James', audioCode: 'JAM', folderName: '59-james', testament: 'new' },
    { bookIndex: 60, bookId: '1-peter', name: '1 Peter', audioCode: '1PE', folderName: '60-1peter', testament: 'new' },
    { bookIndex: 61, bookId: '2-peter', name: '2 Peter', audioCode: '2PE', folderName: '61-2peter', testament: 'new' },
    { bookIndex: 62, bookId: '1-john', name: '1 John', audioCode: '1JO', folderName: '62-1john', testament: 'new' },
    { bookIndex: 63, bookId: '2-john', name: '2 John', audioCode: '2JO', folderName: '63-2john', testament: 'new' },
    { bookIndex: 64, bookId: '3-john', name: '3 John', audioCode: '3JO', folderName: '64-3john', testament: 'new' },
    { bookIndex: 65, bookId: 'jude', name: 'Jude', audioCode: 'JDE', folderName: '65-jude', testament: 'new' },
    { bookIndex: 66, bookId: 'revelation', name: 'Revelation', audioCode: 'REV', folderName: '66-revelation', testament: 'new' },
];

const booksById = new Map(BOOKS.map((book) => [book.bookId, book]));
const booksByIndex = new Map(BOOKS.map((book) => [book.bookIndex, book]));

module.exports = {
    BOOKS,
    booksById,
    booksByIndex,
};